# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_app.py for LongPlay Studio V5.5
import os, glob

block_cipher = None
BASE = os.path.dirname(os.path.abspath(SPEC))

# Native modules
native_modules = [('/Volumes/Data Surakh/0.Vibecode/MRG-LONGPLAY-STUDIO-COMPLETE-2-3-5.10.0/longplay.cpython-39-darwin.so', '.')]
for so in glob.glob(os.path.join(BASE, '*.so')):
    native_modules.append((so, '.'))
for dylib in glob.glob(os.path.join(BASE, '*.dylib')):
    native_modules.append((dylib, '.'))

a = Analysis(
    ['gui.py'],
    pathex=[BASE],
    binaries=native_modules,
    datas=[
        ('Logo.jpg', '.'),
        ('modules', 'modules'),
        ('gui', 'gui'),
    ],
    hiddenimports=[
        # ── Native engines ──
        'longplay',
        'longplay_cpp',
        # ── modules.master ─��
        'modules.master',
        'modules.master.chain',
        'modules.master.rust_chain',
        'modules.master.equalizer',
        'modules.master.dynamics',
        'modules.master.imager',
        'modules.master.maximizer',
        'modules.master.limiter',
        'modules.master.loudness',
        'modules.master.analyzer',
        'modules.master.ai_assist',
        'modules.master.ai_master',
        'modules.master.genre_profiles',
        'modules.master.match_eq',
        'modules.master.realtime_monitor',
        'modules.master.ab_compare',
        'modules.master.loudness_report',
        'modules.master.audio_io',
        'modules.master.ui_panel',
        'modules.master.meter_panels',
        'modules.master.pipeline',
        'modules.master.maximizer',
        'modules.master.resonance_suppressor',
        'modules.master.soothe',
        'modules.master.soothe2_pro',
        'modules.master.tonal_balance',
        'modules.master.playlist_spectral_compressor',
        'modules.master.undo',
        # ── modules.lipsync ──
        'modules.lipsync',
        'modules.lipsync.dreemina_client',
        # ── modules.upload ──
        'modules.upload',
        'modules.upload.youtube_upload',
        # ── modules.widgets ──
        'modules.widgets',
        'modules.widgets.loudness_history',
        'modules.widgets.rotary_knob',
        'modules.widgets.spectrum_analyzer',
        'modules.widgets.tonal_balance',
        'modules.widgets.transfer_curve',
        'modules.widgets.vectorscope',
        # ── gui core ──
        'gui',
        'gui.main',
        'gui._original_helpers',
        'gui.audio_player',
        'gui.styles',
        'gui.styles_vintage',
        # ── gui.utils ──
        'gui.utils',
        'gui.utils.compat',
        'gui.utils.profiler',
        # ── gui.models ──
        'gui.models',
        'gui.models.track',
        'gui.models.commands',
        'gui.models.keyframes',
        'gui.models.effects',
        'gui.models.transitions',
        'gui.models.export_presets',
        'gui.models.autosave',
        # ── gui.widgets ──
        'gui.widgets',
        'gui.widgets.collapsible',
        'gui.widgets.drop_zone',
        'gui.widgets.meter',
        'gui.widgets.rotary_knob',
        'gui.widgets.spectrum_analyzer',
        'gui.widgets.transfer_curve',
        'gui.widgets.vectorscope',
        'gui.widgets.waveform',
        'gui.widgets.wlm_meter',
        # ── gui.dialogs ──
        'gui.dialogs',
        'gui.dialogs.ai_dj',
        'gui.dialogs.ai_video',
        'gui.dialogs.content_factory',
        'gui.dialogs.hook_extractor',
        'gui.dialogs.lipsync_dialog',
        'gui.dialogs.publish_dialog',
        'gui.dialogs.timestamp',
        'gui.dialogs.video_prompt',
        'gui.dialogs.youtube_gen',
        # ── gui.timeline ──
        'gui.timeline',
        'gui.timeline.canvas',
        'gui.timeline.capcut_timeline',
        'gui.timeline.clip_drag',
        'gui.timeline.clip_trim',
        'gui.timeline.history_panel',
        'gui.timeline.keyframe_editor',
        'gui.timeline.multi_track_timeline',
        'gui.timeline.speed_ramp',
        'gui.timeline.text_layer',
        'gui.timeline.track_list',
        # ── gui.video ──
        'gui.video',
        'gui.video.detached',
        'gui.video.gpu_preview',
        'gui.video.multi_track_export',
        'gui.video.preview',
        # ── gui.content_factory ──
        'gui.content_factory',
        'gui.content_factory.batch_master',
        'gui.content_factory.long_builder',
        'gui.content_factory.metadata',
        'gui.content_factory.models',
        'gui.content_factory.planner',
        'gui.content_factory.short_builder',
        'gui.content_factory.workers',
        # ── Third-party ──
        'numpy',
        'scipy',
        'scipy.signal',
        'soundfile',
        'pedalboard',
        'pyloudnorm',
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtMultimedia',
        'PyQt6.QtMultimediaWidgets',
        # PySide6 fallback (optional — if PyQt6 unavailable)
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
    ],
    hookspath=[],
    excludes=['tkinter', 'matplotlib', 'IPython', 'jupyter', 'test', 'tests', 'PySide2'],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='LongPlay Studio',
    debug=False,
    strip=False,
    upx=False,
    console=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name='LongPlay Studio',
)

app = BUNDLE(
    coll,
    name='LongPlay Studio.app',
    icon=None,
    bundle_identifier='com.mrg.longplay-studio',
    info_plist={
        'CFBundleName': 'LongPlay Studio',
        'CFBundleDisplayName': 'LongPlay Studio V5.9',
        'CFBundleVersion': '5.10.0',
        'CFBundleShortVersionString': '5.9',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '13.0',
        'NSMicrophoneUsageDescription': 'LongPlay Studio needs microphone access for audio monitoring.',
    },
)
